### ISSUE TITLE
Screen Reader Research

### ISSUE THREAD

**Issue by Rephraim** [Rephraim/junior-design#2]
Questions to Answer:
How do screen readers interpret HTML elements?
What methods can we use to control screen reader output?
How does this differ across different screen readers?

**Comment by mmoghaddam385** [comment]
Screen readers read the contents within tags, behavior can be modified with aria tags. [label tag](https://www.w3.org/TR/wai-aria-1.1/#aria-label) looks promising.

screen readers should all conform the the [standard](https://www.w3.org/TR/html-aria/#rules-wd) described by the w3 organization.
